### ISSUE TITLE
A problem in train function which miss 1 required positional argument: "train_pseudo_ground_truth_path"

### ISSUE THREAD

**Issue by jucaizhai** [alexklwong/stereoscopic-universal-perturbations#1]
Hi, thank you for your paper and code! This work is wonderful.
I meet a question. When train sups, there have a error occur.
The **train** function  in train_perturb_model.py  miss 1 required positional argument: "train_pseudo_ground_truth_path", how could we solve it?

**Comment by alexklwong** [comment]
Hi and thanks for your interest!

Sorry that was an artifact of auto renaming parameters across files. The optimization does not require ground truth so all ground truth path instances have been removed and pseudo ground truth is added in as optional parameter (only used for AANet).

We just pushed a fix in https://github.com/alexklwong/stereoscopic-universal-perturbations/commit/4ccb2902e5a4f567b5081ad087e53dbe624d595c

You can fetch the fetch the latest version for the fix.

**Comment by jucaizhai** [comment]
OK, thank you!
