### ISSUE TITLE
Pretrained model and pretained SUPs google drive link invalidation issue

### ISSUE THREAD

**Issue by Ljc-NTU** [alexklwong/stereoscopic-universal-perturbations#2]
When I was setting up pretrained stereo models and setting up pretrained SUPs, there was no way to get the files from the Google drive link. There is error 404!

**Comment by alexklwong** [comment]
Hi, this might be because of change in Google Drive limits for Universities that was enacted this past month. I will move them to Sharepoint or another Google Drive.

**Comment by JosephGeoBenjamin** [comment]
Hi,
Where can I find these checkpoints currently? 
the links drive links in code doesn't seem to work.
